<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LabResultsService.Repository\LabResultsService.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="LabResultServices\" />
  </ItemGroup>

</Project>
